### ISSUE TITLE
麻烦提供一下googl云盘的模型链接

### ISSUE THREAD

**Issue by xujin1184104394** [HRNet/HRNet-Object-Detection#19] opened 2019-07-29 09:13 UTC
麻烦提供一下googl云盘的模型链接，谢谢。

**Comment by wondervictor** [comment] 2019-08-11 08:11
All models have been uploaded to BaiduDrive. Links are listed in README. @xujin1184104394

**Comment by wondervictor** [comment] 2019-08-11 08:15
Duplicate of #7 
closed for duplicated issue

**Closed by wondervictor** 2019-08-11 08:15 UTC
