### ISSUE TITLE
提供一下预训练模型的权重下载啊。

### ISSUE THREAD

**Issue by xujin1184104394** [HRNet/HRNet-Object-Detection#18] opened 2019-07-29 09:10 UTC
为什么要使用微软云盘，打开什么都没有？？？

**Comment by wondervictor** [comment] 2019-08-09 02:59
For pretrained models, you can download them through [HRNet-Image-Classification](https://github.com/HRNet/HRNet-Image-Classification
Models trained on COCO will be updated soon.

**Comment by wondervictor** [comment] 2019-08-09 03:00
Duplicate of #20

**Comment by wondervictor** [comment] 2019-08-11 08:11
All models have been uploaded to BaiduDrive. Links are listed in README

**Closed by wondervictor** 2019-08-11 08:11 UTC
